### ISSUE TITLE
msrest dependency conflict

### ISSUE THREAD

**Issue by nidhaloff** [microsoft/azure-devops-python-api#445]
Hey y'all

I have a project, where I want to use this lib and the azure-storage-blob lib. I'm having a dependency conflict since this lib requires `"msrest>=0.7.1,<0.8.0"`. 

This is the error I'm getting:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
azure-devops 6.0.0b4 requires msrest<0.7.0,>=0.6.0, but you have msrest 0.7.1 which is incompatible.
```

You can reproduce the error by creating a virtualenv and running:

`pip install azure-storage-blob && pip install azure-devops`

Right now, I'm not using the library because of this issue, but I find it very handy and would like to use it. Do you have any solution or workaround for this issue?

**Comment by nechvatalp** [comment]
@nidhaloff Hi, we just released new version of the library it now depends on the latest version 0.7.1 which should resolve your conflict. Give the latest version a try.

**Comment by nidhaloff** [comment]
@nechvatalp Thanks, I will try it out!
Is a stable release planned? And an overview of the changes in the release page would be nice

**Comment by dciborow** [comment]
> @nidhaloff Hi, we just released new version of the library it now depends on the latest version 0.7.1 which should resolve your conflict. Give the latest version a try.

I'm still having issues with my project, where I am also using azure-identity. Once I install azure-devops everything with azure-identity breaks.

I believe msrest is deprecated, and that it probably needs to be switched for using azure-identity in here.
