### ISSUE TITLE
update_release_definition wiping queue details

### ISSUE THREAD

**Issue by karann-jain** [Microsoft/azure-devops-python-api#62]
I am trying to clone an environment, apparently the queue details are getting wiped off when i perform a release definition update.

I tried just getting the release definition and performing an update without modifying the object, its wiping off the queue details.

![image](https://user-images.githubusercontent.com/20437699/39430636-f4beb23a-4cab-11e8-952c-ea6561926064.png)

Could you please help.

I am using 0.1.4 vsts and below the client class

```
client = get_connection(team_collection).get_client('vsts.release.v4_1.release_client.ReleaseClient')
```

**Comment by tedchamb** [comment]
@karann-jain Can you add the following line to your code, and let me know the request and response information for the two calls?  ensure you scrub any private data.  We are looking to see at which point the queue information is ignored.

`logging.basicConfig(level=logging.DEBUG)`

Thanks,
Ted

**Comment by karann-jain** [comment]
Additionally, i am not sure why these exceptions are raised, These are very random.

> Traceback (most recent call last):
>   File "/home/karan/PycharmProjects/vsts-automation/sample.py", line 15, in <module>
>     response_put_rd = client.update_release_definition(project=team_project, release_definition=request_rd)
>   File "/usr/local/lib/python3.5/dist-packages/vsts/release/v4_1/release_client.py", line 300, in update_release_definition
>     content=content)
>   File "/usr/local/lib/python3.5/dist-packages/vsts/vss_client.py", line 90, in _send
>     response = self._send_request(request=request, headers=headers, content=content)
>   File "/usr/local/lib/python3.5/dist-packages/vsts/vss_client.py", line 59, in _send_request
>     self._handle_error(request, response)
>   File "/usr/local/lib/python3.5/dist-packages/vsts/vss_client.py", line 235, in _handle_error
>     raise VstsServiceError(wrapped_exception)
> vsts.exceptions.VstsServiceError: VS402875: Release definition needs to have at least one environment. Add an environment and try again.

or sometimes this exception, upon retry this goes away.

> Traceback (most recent call last):
>   File "/home/karan/PycharmProjects/vsts-automation/sample.py", line 15, in <module>
>     response_put_rd = client.update_release_definition(project=team_project, release_definition=request_rd)
>   File "/usr/local/lib/python3.5/dist-packages/vsts/release/v4_1/release_client.py", line 300, in update_release_definition
>     content=content)
>   File "/usr/local/lib/python3.5/dist-packages/vsts/vss_client.py", line 90, in _send
>     response = self._send_request(request=request, headers=headers, content=content)
>   File "/usr/local/lib/python3.5/dist-packages/vsts/vss_client.py", line 59, in _send_request
>     self._handle_error(request, response)
>   File "/usr/local/lib/python3.5/dist-packages/vsts/vss_client.py", line 235, in _handle_error
>     raise VstsServiceError(wrapped_exception)
> vsts.exceptions.VstsServiceError: VS402876: Release definition name cannot be empty. Specify a name and try again.

or sometimes this exception, upon retry this goes away

> Traceback (most recent call last):
>   File "/home/karan/PycharmProjects/vsts-automation/sample.py", line 16, in <module>
>     response_put_rd = client.update_release_definition(project=team_project, release_definition=request_rd)
>   File "/usr/local/lib/python3.5/dist-packages/vsts/release/v4_1/release_client.py", line 300, in update_release_definition
>     content=content)
>   File "/usr/local/lib/python3.5/dist-packages/vsts/vss_client.py", line 90, in _send
>     response = self._send_request(request=request, headers=headers, content=content)
>   File "/usr/local/lib/python3.5/dist-packages/vsts/vss_client.py", line 59, in _send_request
>     self._handle_error(request, response)
>   File "/usr/local/lib/python3.5/dist-packages/vsts/vss_client.py", line 235, in _handle_error
>     raise VstsServiceError(wrapped_exception)
> vsts.exceptions.VstsServiceError: VS402936: Release definition with id 0 does not exist. Specify a valid id and try again.

**Comment by karann-jain** [comment]
Here is the debug log, i couldn't find Hosted anywhere on the response for GET, I assume the same isn't get passed on to PUT as well.

```
 / usr / bin / python3.5 / home / karan / PycharmProjects / vsts - automation / sample.py
DEBUG: root: Loading cache file: /home/karan / .vsts / python - sdk / cache / resources.json
DEBUG: root: attempting to read file / home / karan / .vsts / python - sdk / cache / resources.json as utf - 8 - sig
DEBUG: root: File cache hit for resources on: https: //<my-vsts-base-url>
DEBUG: root: Loading cache file: /home/karan / .vsts / python - sdk / cache / options.json
DEBUG: root: attempting to read file / home / karan / .vsts / python - sdk / cache / options.json as utf - 8 - sig
DEBUG: root: File cache hit for options on: https: //<my-vsts-rm-base-url>
DEBUG: root: Route template: {
	project
}
/_apis/{
	area
}
/{resource}/{
	definitionId
}
DEBUG: root: Api version '4.1-preview.3'
DEBUG: root: GET https: //<my-vsts-rm-base-url>/<my-project-name>/_apis/Release/definitions/105
DEBUG: root: Request content: None
DEBUG: msrest.pipeline: Configuring request: timeout = 100, verify = True, cert = None
	DEBUG: msrest.pipeline: Configuring proxies: ''
	DEBUG: msrest.pipeline: Evaluate proxies against ENV settings: True
	DEBUG: msrest.pipeline: Configuring redirects: allow = True, max = 30
	DEBUG: msrest.pipeline: Configuring retry: max_retries = 3, backoff_factor = 0.8, max_backoff = 90
	DEBUG: urllib3.connectionpool: Starting new HTTPS connection(1): <my-vs-account>.vsrm.visualstudio.com
	DEBUG: urllib3.connectionpool: https: //<my-vsts-rm-base-url>:443 "GET /<my-project-name>/_apis/Release/definitions/105 HTTP/1.1" 200 2175
	DEBUG: root: Response content: b '{
	"source": "userInterface",
	"revision": 39,
	"description": null,
	"createdBy": {
		"displayName": "<my-account-name>",
		"url": "https://app.vssps.visualstudio.com/<my-project-identity-guid>/_apis/Identities/<my-identity-guid>",
		"_links": {
			"avatar": {
				"href": ""
			}
		},
		"id": "<my-identity-guid>",
		"uniqueName": "<my-email>",
		"imageUrl": "https://<my-vsts-base-url>/_api/_common/identityImage?id=<my-identity-guid>",
		"descriptor": "aad.MzMyYzc0ZjUtOWQ5OS03NmMxLTkyYWYtNDg4ZDM1Njk2M2Nk"
	},
	"createdOn": "2018-04-27T14:33:05.447Z",
	"modifiedBy": {
		"displayName": "<my-account-name>",
		"url": "https://app.vssps.visualstudio.com/<my-project-identity-guid>/_apis/Identities/<my-identity-guid>",
		"_links": {
			"avatar": {
				"href": ""
			}
		},
		"id": "<my-identity-guid>",
		"uniqueName": "<my-email>",
		"imageUrl": "https://<my-vsts-base-url>/_api/_common/identityImage?id=<my-identity-guid>",
		"descriptor": "aad.MzMyYzc0ZjUtOWQ5OS03NmMxLTkyYWYtNDg4ZDM1Njk2M2Nk"
	},
	"modifiedOn": "2018-05-01T05:52:34.873Z",
	"isDeleted": false,
	"variables": {
		"JENKINS_JOB_NAME": {
			"value": "<my-jenkins-job-name>_DEPLOY"
		}
	},
	"variableGroups": [],
	"environments": [{
			"id": 589,
			"name": "dev",
			"rank": 1,
			"owner": {
				"displayName": "<my-account-name>",
				"url": "https://app.vssps.visualstudio.com/<my-project-identity-guid>/_apis/Identities/<my-identity-guid>",
				"_links": {
					"avatar": {
						"href": ""
					}
				},
				"id": "<my-identity-guid>",
				"uniqueName": "<my-email>",
				"imageUrl": "https://<my-vsts-base-url>/_api/_common/identityImage?id=<my-identity-guid>",
				"descriptor": "aad.MzMyYzc0ZjUtOWQ5OS03NmMxLTkyYWYtNDg4ZDM1Njk2M2Nk"
			},
			"variables": {},
			"variableGroups": [],
			"preDeployApprovals": {
				"approvals": [{
						"rank": 1,
						"isAutomated": false,
						"isNotificationOn": false,
						"approver": {
							"displayName": "<my-account-name>",
							"url": "https://app.vssps.visualstudio.com/<my-project-identity-guid>/_apis/Identities/<my-identity-guid>",
							"_links": {
								"avatar": {
									"href": ""
								}
							},
							"id": "<my-identity-guid>",
							"uniqueName": "<my-email>",
							"imageUrl": "https://<my-vsts-base-url>/_api/_common/identityImage?id=<my-identity-guid>",
							"descriptor": "aad.MzMyYzc0ZjUtOWQ5OS03NmMxLTkyYWYtNDg4ZDM1Njk2M2Nk"
						},
						"id": 1962
					}
				],
				"approvalOptions": {
					"requiredApproverCount": null,
					"releaseCreatorCanBeApprover": true,
					"autoTriggeredAndPreviousEnvironmentApprovedCanBeSkipped": false,
					"enforceIdentityRevalidation": false,
					"timeoutInMinutes": 0,
					"executionOrder": "beforeGates"
				}
			},
			"deployStep": {
				"id": 1963
			},
			"postDeployApprovals": {
				"approvals": [{
						"rank": 1,
						"isAutomated": true,
						"isNotificationOn": false,
						"id": 1964
					}
				],
				"approvalOptions": {
					"requiredApproverCount": null,
					"releaseCreatorCanBeApprover": true,
					"autoTriggeredAndPreviousEnvironmentApprovedCanBeSkipped": false,
					"enforceIdentityRevalidation": false,
					"timeoutInMinutes": 0,
					"executionOrder": "afterSuccessfulGates"
				}
			},
			"deployPhases": [{
					"deploymentInput": {
						"parallelExecution": {
							"parallelExecutionType": "none"
						},
						"skipArtifactsDownload": false,
						"artifactsDownloadInput": {
							"downloadInputs": [{
									"artifactItems": [],
									"alias": "<my-jenkins-job-name>_BUILD",
									"artifactType": "Jenkins",
									"artifactDownloadMode": "All"
								}
							]
						},
						"queueId": 125,
						"demands": [],
						"enableAccessToken": false,
						"timeoutInMinutes": 0,
						"jobCancelTimeoutInMinutes": 1,
						"condition": "succeeded()",
						"overrideInputs": {}
					},
					"rank": 1,
					"phaseType": "agentBasedDeployment",
					"name": "dev",
					"workflowTasks": [{
							"taskId": "6c731c3c-3c68-459a-a5c9-bde6e6595b5b",
							"version": "3.*",
							"name": "Shell Script ",
							"refName": "",
							"enabled": true,
							"alwaysRun": false,
							"continueOnError": false,
							"timeoutInMinutes": 0,
							"definitionType": "task",
							"overrideInputs": {},
							"condition": "succeeded()",
							"inputs": {
								"targetType": "inline",
								"filePath": "",
								"arguments": "",
								"script": "echo \\" Hello \\ "",
								"workingDirectory": "",
								"failOnStderr": "false"
							}
						}
					]
				}
			],
			"environmentOptions": {
				"emailNotificationType": "OnlyOnFailure",
				"emailRecipients": "release.environment.owner;release.creator",
				"skipArtifactsDownload": false,
				"timeoutInMinutes": 0,
				"enableAccessToken": false,
				"publishDeploymentStatus": true,
				"badgeEnabled": false,
				"autoLinkWorkItems": false,
				"pullRequestDeploymentEnabled": false
			},
			"demands": [],
			"conditions": [],
			"executionPolicy": {
				"concurrencyCount": 0,
				"queueDepthCount": 0
			},
			"schedules": [],
			"currentRelease": {
				"id": 2622,
				"url": "https://<my-vsts-rm-base-url>/<my-project-name>/_apis/Release/releases/2622",
				"_links": {}
			},
			"retentionPolicy": {
				"daysToKeep": 30,
				"releasesToKeep": 3,
				"retainBuild": true
			},
			"processParameters": {},
			"properties": {},
			"preDeploymentGates": {
				"id": 0,
				"gatesOptions": {
					"isEnabled": false,
					"timeout": 1440,
					"samplingInterval": 15,
					"stabilizationTime": 15
				},
				"gates": []
			},
			"postDeploymentGates": {
				"id": 0,
				"gatesOptions": {
					"isEnabled": false,
					"timeout": 1440,
					"samplingInterval": 15,
					"stabilizationTime": 15
				},
				"gates": []
			},
			"environmentTriggers": [],
			"badgeUrl": "https://<my-vsts-rm-base-url>/_apis/public/Release/badge/<my-project-guid>/105/589"
		}
	],
	"artifacts": [{
			"sourceId": "<my-jenkins-guid>:<my-jenkins-job-name>_BUILD",
			"type": "Jenkins",
			"alias": "<my-jenkins-job-name>_BUILD",
			"definitionReference": {
				"artifactSourceDefinitionUrl": {
					"id": "https://<my-jenkins-host>/jenkins//job/<my-jenkins-job-name>_BUILD",
					"name": ""
				},
				"connection": {
					"id": "<my-jenkins-guid>",
					"name": "Jenkins Server"
				},
				"defaultVersionType": {
					"id": "selectDuringReleaseCreationType",
					"name": "Specify at the time of release creation"
				},
				"definition": {
					"id": "<my-jenkins-job-name>_BUILD",
					"name": "<my-jenkins-job-name>_BUILD"
				}
			},
			"isPrimary": true
		}
	],
	"triggers": [],
	"releaseNameFormat": "",
	"tags": [],
	"properties": {
		"DefinitionCreationSource": {
			"$type": "System.String",
			"$value": "ReleaseClone"
		},
		"$type": {
			"$type": "System.String",
			"$value": "System.String"
		}
	},
	"id": 105,
	"name": "test_1",
	"path": "\\\\",
	"projectReference": null,
	"url": "https://<my-vsts-rm-base-url>/<my-project-guid>/_apis/Release/definitions/105",
	"_links": {
		"self": {
			"href": "https://<my-vsts-rm-base-url>/<my-project-guid>/_apis/Release/definitions/105"
		},
		"web": {
			"href": "https://<my-vsts-base-url>/<my-project-guid>/_release?definitionId=105"
		}
	}
}
'
	DEBUG: root: Route template: {
	project
}
/_apis/{
	area
}
/{resource}/{
	definitionId
}
DEBUG: root: Api version '4.1-preview.3'
DEBUG: root: PUT https: //<my-vsts-rm-base-url>/<my-project-name>/_apis/Release/definitions
DEBUG: root: Request content: {
	'properties': {
		'DefinitionCreationSource': {
			'$type': 'System.String',
			'$value': 'ReleaseClone'
		},
		'$type': {
			'$type': 'System.String',
			'$value': 'System.String'
		}
	},
	'isDeleted': False,
	'environments': [{
			'properties': {},
			'rank': 1,
			'environmentOptions': {
				'timeoutInMinutes': 0,
				'emailNotificationType': 'OnlyOnFailure',
				'publishDeploymentStatus': True,
				'skipArtifactsDownload': False,
				'badgeEnabled': False,
				'autoLinkWorkItems': False,
				'enableAccessToken': False,
				'emailRecipients': 'release.environment.owner;release.creator'
			},
			'retentionPolicy': {
				'retainBuild': True,
				'daysToKeep': 30,
				'releasesToKeep': 3
			},
			'postDeployApprovals': {
				'approvalOptions': {
					'enforceIdentityRevalidation': False,
					'timeoutInMinutes': 0,
					'releaseCreatorCanBeApprover': True,
					'autoTriggeredAndPreviousEnvironmentApprovedCanBeSkipped': False,
					'executionOrder': 'afterSuccessfulGates'
				},
				'approvals': [{
						'rank': 1,
						'id': 1964,
						'isNotificationOn': False,
						'isAutomated': True
					}
				]
			},
			'deployStep': {
				'id': 1963
			},
			'owner': {
				'descriptor': 'aad.MzMyYzc0ZjUtOWQ5OS03NmMxLTkyYWYtNDg4ZDM1Njk2M2Nk',
				'displayName': '<my-account-name>',
				'url': 'https://app.vssps.visualstudio.com/<my-project-identity-guid>/_apis/Identities/<my-identity-guid>',
				'imageUrl': 'https://<my-vsts-base-url>/_api/_common/identityImage?id=<my-identity-guid>',
				'id': '<my-identity-guid>',
				'_links': {},
				'uniqueName': '<my-email>'
			},
			'conditions': [],
			'preDeployApprovals': {
				'approvalOptions': {
					'enforceIdentityRevalidation': False,
					'timeoutInMinutes': 0,
					'releaseCreatorCanBeApprover': True,
					'autoTriggeredAndPreviousEnvironmentApprovedCanBeSkipped': False,
					'executionOrder': 'beforeGates'
				},
				'approvals': [{
						'rank': 1,
						'id': 1962,
						'approver': {
							'descriptor': 'aad.MzMyYzc0ZjUtOWQ5OS03NmMxLTkyYWYtNDg4ZDM1Njk2M2Nk',
							'displayName': '<my-account-name>',
							'url': 'https://app.vssps.visualstudio.com/<my-project-identity-guid>/_apis/Identities/<my-identity-guid>',
							'imageUrl': 'https://<my-vsts-base-url>/_api/_common/identityImage?id=<my-identity-guid>',
							'id': '<my-identity-guid>',
							'_links': {},
							'uniqueName': '<my-email>'
						},
						'isNotificationOn': False,
						'isAutomated': False
					}
				]
			},
			'id': 589,
			'variableGroups': [],
			'executionPolicy': {
				'concurrencyCount': 0,
				'queueDepthCount': 0
			},
			'variables': {},
			'badgeUrl': 'https://<my-vsts-rm-base-url>/_apis/public/Release/badge/<my-project-guid>/105/589',
			'name': 'dev',
			'demands': [],
			'postDeploymentGates': {
				'gatesOptions': {
					'timeout': 1440,
					'stabilizationTime': 15,
					'samplingInterval': 15,
					'isEnabled': False
				},
				'id': 0,
				'gates': []
			},
			'deployPhases': [{
					'name': 'dev',
					'rank': 1,
					'phaseType': 'agentBasedDeployment',
					'workflowTasks': [{
							'overrideInputs': {},
							'inputs': {
								'script': 'echo "Hello"',
								'failOnStderr': 'false',
								'arguments': '',
								'targetType': 'inline',
								'workingDirectory': '',
								'filePath': ''
							},
							'enabled': True,
							'name': 'Shell Script ',
							'condition': 'succeeded()',
							'alwaysRun': False,
							'refName': '',
							'taskId': '6c731c3c-3c68-459a-a5c9-bde6e6595b5b',
							'timeoutInMinutes': 0,
							'continueOnError': False,
							'version': '3.*',
							'definitionType': 'task'
						}
					]
				}
			],
			'preDeploymentGates': {
				'gatesOptions': {
					'timeout': 1440,
					'stabilizationTime': 15,
					'samplingInterval': 15,
					'isEnabled': False
				},
				'id': 0,
				'gates': []
			},
			'schedules': [],
			'processParameters': {}
		}
	],
	'path': '\\',
	'triggers': [],
	'variableGroups': [],
	'name': 'test_1',
	'id': 105,
	'artifacts': [{
			'isPrimary': True,
			'type': 'Jenkins',
			'definitionReference': {
				'connection': {
					'name': 'Jenkins Server',
					'id': '<my-jenkins-guid>'
				},
				'artifactSourceDefinitionUrl': {
					'name': '',
					'id': 'https://<my-jenkins-host>/jenkins//job/<my-jenkins-job-name>_BUILD'
				},
				'definition': {
					'name': '<my-jenkins-job-name>_BUILD',
					'id': '<my-jenkins-job-name>_BUILD'
				},
				'defaultVersionType': {
					'name': 'Specify at the time of release creation',
					'id': 'selectDuringReleaseCreationType'
				}
			},
			'sourceId': '<my-jenkins-guid>:<my-jenkins-job-name>_BUILD',
			'alias': '<my-jenkins-job-name>_BUILD'
		}
	],
	'revision': 39,
	'releaseNameFormat': '',
	'_links': {},
	'source': 'userInterface',
	'url': 'https://<my-vsts-rm-base-url>/<my-project-guid>/_apis/Release/definitions/105',
	'modifiedBy': {
		'descriptor': 'aad.MzMyYzc0ZjUtOWQ5OS03NmMxLTkyYWYtNDg4ZDM1Njk2M2Nk',
		'displayName': '<my-account-name>',
		'url': 'https://app.vssps.visualstudio.com/<my-project-identity-guid>/_apis/Identities/<my-identity-guid>',
		'imageUrl': 'https://<my-vsts-base-url>/_api/_common/identityImage?id=<my-identity-guid>',
		'id': '<my-identity-guid>',
		'_links': {},
		'uniqueName': '<my-email>'
	},
	'variables': {
		'JENKINS_JOB_NAME': {
			'value': '<my-jenkins-job-name>_DEPLOY'
		}
	},
	'tags': [],
	'modifiedOn': '2018-05-01T05:52:34.873Z',
	'createdOn': '2018-04-27T14:33:05.44699999999999995Z',
	'createdBy': {
		'descriptor': 'aad.MzMyYzc0ZjUtOWQ5OS03NmMxLTkyYWYtNDg4ZDM1Njk2M2Nk',
		'displayName': '<my-account-name>',
		'url': 'https://app.vssps.visualstudio.com/<my-project-identity-guid>/_apis/Identities/<my-identity-guid>',
		'imageUrl': 'https://<my-vsts-base-url>/_api/_common/identityImage?id=<my-identity-guid>',
		'id': '<my-identity-guid>',
		'_links': {},
		'uniqueName': '<my-email>'
	}
}
DEBUG: msrest.pipeline: Configuring request: timeout = 100, verify = True, cert = None
	DEBUG: msrest.pipeline: Configuring proxies: ''
	DEBUG: msrest.pipeline: Evaluate proxies against ENV settings: True
	DEBUG: msrest.pipeline: Configuring redirects: allow = True, max = 30
	DEBUG: msrest.pipeline: Configuring retry: max_retries = 3, backoff_factor = 0.8, max_backoff = 90
	DEBUG: urllib3.connectionpool: Starting new HTTPS connection(1): <my-vs-account>.vsrm.visualstudio.com
	DEBUG: urllib3.connectionpool: https: //<my-vsts-rm-base-url>:443 "PUT /<my-project-name>/_apis/Release/definitions HTTP/1.1" 200 2273
	DEBUG: root: Response content: b '{
	"source": "userInterface",
	"revision": 40,
	"description": null,
	"createdBy": {
		"displayName": "<my-account-name>",
		"displayName": "<my-account-name>",
		"url": "https://app.vssps.visualstudio.com/<my-project-identity-guid>/_apis/Identities/<my-identity-guid>",
		"_links": {
			"avatar": {
				"href": ""
			}
		},
		"id": "<my-identity-guid>",
		"uniqueName": "<my-email>",
		"imageUrl": "https://<my-vsts-base-url>/_api/_common/identityImage?id=<my-identity-guid>",
		"descriptor": "aad.MzMyYzc0ZjUtOWQ5OS03NmMxLTkyYWYtNDg4ZDM1Njk2M2Nk"
	},
	"createdOn": "2018-04-27T14:33:05.447Z",
	"modifiedBy": {
		"displayName": "<my-build-account-name>",
		"url": "https://app.vssps.visualstudio.com/<my-project-identity-guid>/_apis/Identities/<my-build-account-guid>",
		"_links": {
			"avatar": {
				"href": ""
			}
		},
		"id": "<my-build-account-guid>",
		"uniqueName": "<my-buildaccount-email>",
		"imageUrl": "https://<my-vsts-base-url>/_api/_common/identityImage?id=<my-build-account-guid>",
		"descriptor": "aad.NzcwNTVmOWQtOGIwYS03MTYyLWE0MjItOWJiNWZjYjQzYzJm"
	},
	"modifiedOn": "2018-05-01T05:53:58.983Z",
	"isDeleted": false,
	"variables": {
		"JENKINS_JOB_NAME": {
			"value": "<my-jenkins-job-name>_DEPLOY"
		}
	},
	"variableGroups": [],
	"environments": [{
			"id": 589,
			"name": "dev",
			"rank": 1,
			"owner": {
				"displayName": "<my-account-name>",
				"url": "https://app.vssps.visualstudio.com/<my-project-identity-guid>/_apis/Identities/<my-identity-guid>",
				"_links": {
					"avatar": {
						"href": ""
					}
				},
				"id": "<my-identity-guid>",
				"uniqueName": "<my-email>",
				"imageUrl": "https://<my-vsts-base-url>/_api/_common/identityImage?id=<my-identity-guid>",
				"descriptor": "aad.MzMyYzc0ZjUtOWQ5OS03NmMxLTkyYWYtNDg4ZDM1Njk2M2Nk"
			},
			"variables": {},
			"variableGroups": [],
			"preDeployApprovals": {
				"approvals": [{
						"rank": 1,
						"isAutomated": false,
						"isNotificationOn": false,
						"approver": {
							"displayName": "<my-account-name>",
							"url": "https://app.vssps.visualstudio.com/<my-project-identity-guid>/_apis/Identities/<my-identity-guid>",
							"_links": {
								"avatar": {
									"href": ""
								}
							},
							"id": "<my-identity-guid>",
							"uniqueName": "<my-email>",
							"imageUrl": "https://<my-vsts-base-url>/_api/_common/identityImage?id=<my-identity-guid>",
							"descriptor": "aad.MzMyYzc0ZjUtOWQ5OS03NmMxLTkyYWYtNDg4ZDM1Njk2M2Nk"
						},
						"id": 1962
					}
				],
				"approvalOptions": {
					"requiredApproverCount": null,
					"releaseCreatorCanBeApprover": true,
					"autoTriggeredAndPreviousEnvironmentApprovedCanBeSkipped": false,
					"enforceIdentityRevalidation": false,
					"timeoutInMinutes": 0,
					"executionOrder": "beforeGates"
				}
			},
			"deployStep": {
				"id": 1963
			},
			"postDeployApprovals": {
				"approvals": [{
						"rank": 1,
						"isAutomated": true,
						"isNotificationOn": false,
						"id": 1964
					}
				],
				"approvalOptions": {
					"requiredApproverCount": null,
					"releaseCreatorCanBeApprover": true,
					"autoTriggeredAndPreviousEnvironmentApprovedCanBeSkipped": false,
					"enforceIdentityRevalidation": false,
					"timeoutInMinutes": 0,
					"executionOrder": "afterSuccessfulGates"
				}
			},
			"deployPhases": [{
					"deploymentInput": {
						"parallelExecution": {
							"parallelExecutionType": "none"
						},
						"skipArtifactsDownload": false,
						"artifactsDownloadInput": {
							"downloadInputs": []
						},
						"queueId": 0,
						"demands": [],
						"enableAccessToken": false,
						"timeoutInMinutes": 0,
						"jobCancelTimeoutInMinutes": 1,
						"condition": "succeeded()",
						"overrideInputs": {}
					},
					"rank": 1,
					"phaseType": "agentBasedDeployment",
					"name": "dev",
					"workflowTasks": [{
							"taskId": "6c731c3c-3c68-459a-a5c9-bde6e6595b5b",
							"version": "3.*",
							"name": "Shell Script ",
							"refName": "",
							"enabled": true,
							"alwaysRun": false,
							"continueOnError": false,
							"timeoutInMinutes": 0,
							"definitionType": "task",
							"overrideInputs": {},
							"condition": "succeeded()",
							"inputs": {
								"script": "echo \\" Hello \\ "",
								"failOnStderr": "false",
								"arguments": "",
								"targetType": "inline",
								"workingDirectory": "",
								"filePath": ""
							}
						}
					]
				}
			],
			"environmentOptions": {
				"emailNotificationType": "OnlyOnFailure",
				"emailRecipients": "release.environment.owner;release.creator",
				"skipArtifactsDownload": false,
				"timeoutInMinutes": 0,
				"enableAccessToken": false,
				"publishDeploymentStatus": true,
				"badgeEnabled": false,
				"autoLinkWorkItems": false,
				"pullRequestDeploymentEnabled": false
			},
			"demands": [],
			"conditions": [],
			"executionPolicy": {
				"concurrencyCount": 0,
				"queueDepthCount": 0
			},
			"schedules": [],
			"currentRelease": {
				"id": 2622,
				"url": "https://<my-vsts-rm-base-url>/<my-project-name>/_apis/Release/releases/2622",
				"_links": {}
			},
			"retentionPolicy": {
				"daysToKeep": 30,
				"releasesToKeep": 3,
				"retainBuild": true
			},
			"processParameters": {},
			"properties": {},
			"preDeploymentGates": {
				"id": 0,
				"gatesOptions": {
					"isEnabled": false,
					"timeout": 1440,
					"samplingInterval": 15,
					"stabilizationTime": 15
				},
				"gates": []
			},
			"postDeploymentGates": {
				"id": 0,
				"gatesOptions": {
					"isEnabled": false,
					"timeout": 1440,
					"samplingInterval": 15,
					"stabilizationTime": 15
				},
				"gates": []
			},
			"environmentTriggers": [],
			"badgeUrl": "https://<my-vsts-rm-base-url>/_apis/public/Release/badge/<my-project-guid>/105/589"
		}
	],
	"artifacts": [{
			"sourceId": "<my-jenkins-guid>:<my-jenkins-job-name>_BUILD",
			"type": "Jenkins",
			"alias": "<my-jenkins-job-name>_BUILD",
			"definitionReference": {
				"artifactSourceDefinitionUrl": {
					"id": "https://<my-jenkins-host>/jenkins//job/<my-jenkins-job-name>_BUILD",
					"name": ""
				},
				"connection": {
					"id": "<my-jenkins-guid>",
					"name": "Jenkins Server"
				},
				"defaultVersionType": {
					"id": "selectDuringReleaseCreationType",
					"name": "Specify at the time of release creation"
				},
				"definition": {
					"id": "<my-jenkins-job-name>_BUILD",
					"name": "<my-jenkins-job-name>_BUILD"
				}
			},
			"isPrimary": true
		}
	],
	"triggers": [],
	"releaseNameFormat": "",
	"tags": [],
	"properties": {
		"DefinitionCreationSource": {
			"$type": "System.String",
			"$value": "ReleaseClone"
		},
		"$type": {
			"$type": "System.String",
			"$value": "System.String"
		}
	},
	"id": 105,
	"name": "test_1",
	"path": "\\\\",
	"projectReference": null,
	"url": "https://<my-vsts-rm-base-url>/<my-project-guid>/_apis/Release/definitions/105",
	"_links": {
		"self": {
			"href": "https://<my-vsts-rm-base-url>/<my-project-guid>/_apis/Release/definitions/105"
		},
		"web": {
			"href": "https://<my-vsts-base-url>/<my-project-guid>/_release?definitionId=105"
		}
	}
}
'
```

Here is the sample used to generate this

```
from vsts.vss_connection import VssConnection
from msrest.authentication import BasicAuthentication
import logging

logging.basicConfig(level=logging.DEBUG)

token = 'my-token'
team_instance = 'my-base-url'
team_project = 'my-project-name'

credentials = BasicAuthentication('', token)
connection = VssConnection(base_url=team_instance, creds=credentials)
client = connection.get_client('vsts.release.v4_1.release_client.ReleaseClient')

request_rd = client.get_release_definition(project=team_project, definition_id=105)
response_put_rd = client.update_release_definition(project=team_project, release_definition=request_rd)

#### Get the Id and add it in the above parameter ####
# response_rd = client.get_release_definitions(project=team_project)
# for release_defintion in response_rd:
#     print(str(release_defintion.id) + "=" + release_defintion.name)

```

**Comment by tedchamb** [comment]
fixing in #63

**Comment by karann-jain** [comment]
@tedchamb The issue with queueId appears to be fixed, however now when i am trying to deepcopy an existing environment and performing an update the request object is sending None for new environment. I tried printing the newly deep copied object and the value exists. am i doing something wrong here?

Note: I changed the name, id and rank of new environment before performing an update

**Comment by karann-jain** [comment]
@tedchamb I think i found the root cause of above exceptions, appears like the order of attributes in the request changes every time client library parses the response and the exceptions are thrown for the last attribute. Which is either environments, id or name. if these are on the top of the request there is no issue, request is successfully processed.

However, when i directly call the vsts api, i see the order of response is always the same, I think client library is somehow changing the order of the response and the same i am sending it back (as per the sample above) which is causing parsing failure on vsts api.

Is there a way to maintain the order of the response received while parsing on the client library?
I noticed the same behavior for all the responses parsed by client library.

**Comment by tedchamb** [comment]
@karann-jain Thanks for the detailed investigation.   This is very helpful. The conversion of response to object and from object to request is done by the MsRest module.  I will look into it to see what we can do form our side.  Json should never be order dependent, so I wouldn't expect this to cause issues.

**Comment by tedchamb** [comment]
@karann-jain  We fixed a bug on the server side recently, which fixes a custom converter on the property bag which was expecting the "$type" property to become before "$value".  This has been fixed to be order independent.  This is most likely the issue you were hitting.  See if you can still repro your remaining issue while targeting the service.

**Comment by karann-jain** [comment]
@tedchamb Thanks for the follow up. 

I tried update for 50 release definitions and below is the failure count

10 of them failed with following error. 
```vsts.exceptions.VstsServiceError: VS402876: Release pipeline name cannot be empty. Specify a name and try again.```

7 of them failed with following error. 
```vsts.exceptions.VstsServiceError: VS402875: Release pipeline needs to have at least one stage. Add a stage and try again.```

No errors for below - This is fixed now 👍 :
vsts.exceptions.VstsServiceError: VS402936: Release definition with id 0 does not exist. Specify a valid id and try again.

Overall i notice good amount of updates to release definition working now. Earlier this was less than 50% success. 👍 🥇

**Comment by tedchamb** [comment]
@karann-jain , can you verify that this is still a problem against the service?  I believe there were some server side changes that were made to fix the remaining issues you were seeing.

**Comment by karann-jain** [comment]
@tedchamb Thanks for the follow up! All the issues appear to be fixed. 👍 🥇 
I tried updating 100 release definitions went through without any error.

**Comment by tedchamb** [comment]
@karann-jain that is great news.  I will close this out.  If you have any more issues, please let us know.
